### ISSUE TITLE
Other implementation

### ISSUE THREAD

**Issue by bablokb** [CedarGroveStudios/SevenSeg_font#1]
Hi,

I came across this site because of your posting in Adafruit-Playground. This is not an issue, I just want to share an alternative.

I am using these fonts: <https://github.com/keshikan/DSEG>. Since these fonts are supplied as ttf, I can create any bdf-size I need using FontForge. But since this is always a bit involved, it is nice to have your fonts directly in BDF format :-).

**Comment by CedarGroveStudios** [comment]
Thanks for sharing the alternative resource. The size flexibility is a real plus.

The SevenSeg font files were originally designed to be very small due to project memory limitations. Now that most of my projects are moving to the ESP32-S3 architecture, font memory usage will likely not be an issue in the future.
